##################################################################################################
# Sample service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: detail-2
  labels:
    app: detail-2
    service: detail-2
spec:
  ports:
  - port: 8084
    name: grpc
  selector:
    app: detail-2
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restaurant-detail-2
  labels:
    account: restaurant-detail-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail-2
  labels:
    app: detail-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detail-2
  template:
    metadata:
      labels:
        app: detail-2
    spec:
      serviceAccountName: restaurant-detail-2
      imagePullSecrets:
      - name: regcred
      containers:
      - name: detail-2
        image: akashvaishuchandni/restaurant_microservice:lab4
        command: ["/app/restaurant-microservice"]
        args: ["detail-2"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8084
        resources:
          limits:
            cpu: 1000m # 1 (virtual if on VM) CPU
