##################################################################################################
# Sample service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: detail-3
  labels:
    app: detail-3
    service: detail-3
spec:
  ports:
  - port: 8085
    name: grpc
  selector:
    app: detail-3
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restaurant-detail-3
  labels:
    account: restaurant-detail-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail-3
  labels:
    app: detail-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detail-3
  template:
    metadata:
      labels:
        app: detail-3
    spec:
      serviceAccountName: restaurant-detail-3
      imagePullSecrets:
      - name: regcred
      containers:
      - name: detail-3
        image: akashvaishuchandni/restaurant_microservice:lab4
        command: ["/app/restaurant-microservice"]
        args: ["detail-3"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        resources:
          limits:
            cpu: 1000m # 1 (virtual if on VM) CPU
