##################################################################################################
# Sample service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: detail-1
  labels:
    app: detail-1
    service: detail-1
spec:
  ports:
  - port: 8081
    name: grpc
  selector:
    app: detail-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restaurant-detail-1
  labels:
    account: restaurant-detail-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: detail-1
  labels:
    app: detail-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: detail-1
  template:
    metadata:
      labels:
        app: detail-1
    spec:
      serviceAccountName: restaurant-detail-1
      imagePullSecrets:
      - name: regcred
      containers:
      - name: detail-1
        image: akashvaishuchandni/restaurant_microservice:lab4
        command: ["/app/restaurant-microservice"]
        args: ["detail-1"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
        resources:
          limits:
            cpu: 1000m # 1 (virtual if on VM) CPU
