##################################################################################################
# review cache service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: mycache-review-3
  labels:
    app: mycache-review-3
    service: mycache-review-3
spec:
  ports:
  - port: 11213
    name: grpc
  selector:
    app: mycache-review-3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycache-review-3
  labels:
    app: mycache-review-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycache-review-3
  template:
    metadata:
      labels:
        app: mycache-review-3
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: mycache-review-3
        image: akashvaishuchandni/restaurant_microservice:lab4
        command: ["/app/restaurant-microservice"]
        args: ["review-3", "cache-3"]
        imagePullPolicy: Always
        ports:
        - containerPort: 11213
        resources:
          limits:
            cpu: 1000m # 1 (virtual if on VM) CPU
          requests:
            cpu: 100m # 100 (virtual) millicpus
        volumeMounts:
        - name: data-volume
          mountPath: /var/lib/data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: mycache-review-3-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mycache-review-3-pv
spec:
  volumeMode: Filesystem
  capacity:
    storage: 1Gi # try changing to 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mycache-review-3-storage
  hostPath:
    path: /data/volumes/mycache-review-3-pv
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mycache-review-3-pvc
spec:
  accessModes:
    - ReadWriteMany # change to ReadWriteMany if multiple pods using (distributed database)
  storageClassName: mycache-review-3-storage
  resources:
    requests:
      storage: 1Gi # try changing to 5Gi
---
