##################################################################################################
# Sample service and deployment
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: review-1
  labels:
    app: review-1
    service: review-1
spec:
  ports:
  - port: 8082
    name: grpc
  selector:
    app: review-1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: restaurant-review-1
  labels:
    account: restaurant-review-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: review-1
  labels:
    app: review-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-1
  template:
    metadata:
      labels:
        app: review-1
    spec:
      serviceAccountName: restaurant-review-1
      imagePullSecrets:
      - name: regcred
      containers:
      - name: review-1
        image: akashvaishuchandni/restaurant_microservice:lab4
        command: ["/app/restaurant-microservice"]
        args: ["review-1"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8082
        resources:
          limits:
            cpu: 1000m # 1 (virtual if on VM) CPU